### ISSUE TITLE
`asdf` isn't in the $PATH, none of asdf installed tools are executable

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/packer-images#1042]
### Reproduction steps

Run this pipeline on infra.ci.jenkins.io:

```groovy
pipeline {
    agent { label 'linux-amd64-docker' }
    stages {
        stage('current') {
            steps {
                sh 'echo "PATH: ${PATH}"'
                sh 'asdf --version || echo "no asdf"'
                sh 'yq --version || echo "no yq"'
            }
        }
        stage('fixed PATH') {
            environment {
                PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin:/usr/local/go/bin"
            }
            steps {
                sh 'asdf --version || echo "no asdf"'
                sh 'yq --version || echo "no yq"'
            }
        }
    }    
}
```

### Expected Results

Both stages show versions: correct $PATH value, `asdf` and `yq` directly executable without fixing $PATH

### Actual Results

Only the "fixed PATH" shows versions:

> \+ asdf --version
>  v0.14.0
>  [Pipeline] sh
>  \+ yq --version
>  yq (https://github.com/mikefarah/yq/) version 4.25.3

The "current" one doesn't:

> \+ echo 'PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:${asdf_install_dir}/shims:${asdf_install_dir}/bin:/usr/local/go/bin'
>  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:${asdf_install_dir}/shims:${asdf_install_dir}/bin:/usr/local/go/bin
>  [Pipeline] sh
>  \+ asdf --version
>  /home/jenkins/workspace/jobs_docker-confluence-data_main@tmp/durable-f9cb9506/script.sh.copy: line 1: asdf: command not found
>  \+ echo 'no asdf'
>  no asdf
>  [Pipeline] sh
>  \+ yq --version
>  /home/jenkins/workspace/jobs_docker-confluence-data_main@tmp/durable-aa430d29/script.sh.copy: line 1: yq: command not found
>  \+ echo 'no yq'

### Anything else?

The culprit seems to come from https://github.com/jenkins-infra/packer-images/blob/a0a34f1826c4a4efc5c76185019d9b89b1c5060b/provisioning/ubuntu-provision.sh#L158-L159

**Comment by smerle33** [comment]
this is coming from https://github.com/jenkins-infra/packer-images/pull/1021

**Comment by dduportal** [comment]
> The culprit seems to come from 


Can you details why would it be this line? It is not really clear

**Comment by dduportal** [comment]
Ran the following pipeline and it confirms @lemeurherve analysis:

```
pipeline {
    agent { label 'linux-amd64-docker' }
    stages {
        stage('helpdesk-1042') {
            steps {
                sh 'cat /etc/environment'
            }
        }
    }    
}
```

results in:

```
09:34:26  + cat /etc/environment
09:34:26  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:${asdf_install_dir}/shims:${asdf_install_dir}/bin:/usr/local/go/bin"
09:34:26  LC_ALL=en_US.UTF-8
09:34:26  JAVA_HOME=/opt/jdk-11
```


wh

**Comment by smerle33** [comment]
the result is now: https://infra.ci.jenkins.io/job/updatecli/job/kubernetes-management/job/main/27733/
```
08:48:25  + cat /etc/environment
08:48:25  PATH="/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin"
08:48:25  LC_ALL=en_US.UTF-8
08:48:25  JAVA_HOME=/opt/jdk-11
```
