### ISSUE TITLE
Use an azure credential instead of multiple string credentials to configure the Service Principal

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/packer-images#183]
https://github.com/jenkins-infra/packer-images/blob/main/Jenkinsfile_k8s#L114-L116

It would be nice to use an azure credential regrouping these 3 values.
Might need an additional plugin.

**Comment by dduportal** [comment]
@timja as per https://plugins.jenkins.io/azure-credentials/, we can use the `withCredential`. Do you know if using the declarative form behaves with the "default" behavior described in https://plugins.jenkins.io/azure-credentials/#plugin-content-using-azurecredentials-in-a-job-freestyle--pipeline?

Eg.. how would the following snippet behave?

```
environment {
  AZURE_CLIENT = credentials('my-super-azure-credential')
}
```

?

**Comment by dduportal** [comment]
Self answer: just tried it and it does not work with the credential form:

```
18:57:06  ERROR: No suitable binding handler could be found for type com.microsoft.azure.util.AzureCredentials. Supported types are StandardUsernamePasswordCredentials,FileCredentials,StringCredentials,DockerServerCredentials,AmazonWebServicesCredentials,SSHUserPrivateKey.
```

Worth a feature request to the plugin?

**Comment by timja** [comment]
Sure, it works on scripted but maybe not declarative

not sure how you would model that

**Comment by dduportal** [comment]
> Sure, it works on scripted but maybe not declarative
> 
> not sure how you would model that

I was thinking something like the `_USR` and `_PSW` trick for the usernamePassword and sshCredentials (ref. https://www.jenkins.io/doc/book/pipeline/syntax/#environment), reusing the same pattern as what the azure-credentials already does in scripted

Something like

```
environment {
  MY_CRED = credentials('my-super-azure-credential')
}

stages {
  stage('build') {
    steps {
      echo "My client id is $MY_CRED_CLIENT_ID"
      echo "My client secret is $MY_CRED_CLIENT_SECRET"
      echo "My tenant id is $MY_CRED_TENANT_ID"
      echo "My subscription id is $MY_CRED_SUBSCRIPTION_ID"
    }
  }
}

```

**Comment by timja** [comment]
could you create an issue please?

**Comment by dduportal** [comment]
> could you create an issue please? https://github.com/jenkinsci/azure-credentials-plugin

Here you are: https://github.com/jenkinsci/azure-credentials-plugin/issues/96 :) 
I wanted to be sure that it made sense + it was applicable. Many thanks for the pointers!

**Comment by lemeurherve** [comment]
Thanks BTW @timja for https://github.com/jenkinsci/azure-credentials-plugin/pull/97!
