### ISSUE TITLE
Builds fail since the tag version now has a "v" prefix

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/packer-images#227]
Since https://github.com/jenkins-infra/packer-images/commit/a07904029994d3e5306e8f45ee6fa9fb2d9093d2 the release-drafter isn't surcharged in this repo, and instead rely only on the [global .github configuration](https://github.com/jenkins-infra/.github/blob/master/.github/release-drafter.yml), which defines (https://github.com/jenkins-infra/.github/blob/dfa1b56452124590001ad12bd305a89c6fa39e04/.github/release-drafter.yml#L2-L3) for version in names and tags:
```
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
```

As a result, the new tags contain a "v" prefix (cf [`0.23.0` vs. `v0.24.0`](https://github.com/jenkins-infra/packer-images/releases)), which isn't accepted and [fail the builds](https://infra.ci.jenkins.io/blue/organizations/jenkins/infra-tools%2Fpacker-images/detail/0.23.0/1/pipeline/377):
<img width="1962" alt="image" src="https://user-images.githubusercontent.com/91831478/168099605-0ab143c8-5e92-4924-968b-4922f8594e47.png">

**Comment by dduportal** [comment]
Looks good, thanks for fixing my mess!

Not important question: is there a reason for not removing the `v`prefix in the packer templates?

**Comment by lemeurherve** [comment]
> removing the `v`prefix in the packer templates?

I don't see what templates you are talking about, do you have a link please?

**Comment by dduportal** [comment]
> 

No problem :) 

I was referring to: https://github.com/jenkins-infra/packer-images/blob/main/jenkins-agent.pkr.hcl#L51 

There is a comment stating the need for a valid semver in Azure, but I'm sure I could have done that better in the packer template, by defining a [local value](https://www.packer.io/docs/templates/hcl_templates/locals) that would [trim the `v` prefix](https://www.packer.io/docs/templates/hcl_templates/functions/string/trimprefix) for instance, or any other HCL function.

**Comment by lemeurherve** [comment]
I see, 👍 
We decided with @smerle33 the version without any prefix was preferable for most/all our builds anyway, so no `v` :)

**Comment by dduportal** [comment]
> I see, 👍
> We decided with @smerle33 the version without any prefix was preferable for most/all our builds anyway, so no `v` :)

Totally make sense, thanks for fixing it globally!
