### ISSUE TITLE
Staging packer images version isn't incremented

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/packer-images#228]
Trying to find why the last azure-arm Windows 2019 don't contains the tools we added, I've noticed the version is hardcoded to 0.0.1 when building on the principal branch (note: "staging" gallery), while it's incremented when building on tags (note: "prod" gallery in Azure portal)

This version is stated as "published in 2021":
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/91831478/168094848-751201ea-8249-4dd5-949d-1ecab4c01a76.png">

While the "timestamp" tag is correct:
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/91831478/168094991-a9c0bfcc-aba8-4b14-8a94-2eb17ef96813.png">

Shouldn't we increment this staging version too so every staging image would have its own published date?
I'm wondering if the absence of our last modifications couldn't be related to this "unique" version.

**Comment by dduportal** [comment]
The version in production until today where incremented, but not staging as it is expected (but totally challengable and changeable)

for staging, specifically, the idea is that we always have 1 build at a time on the principal branch (not enforced though), so we can afford overriding the version and keep a « latest » pattern.
