### ISSUE TITLE
Shared gallery not available

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/packer-images#232]
The main build fails with th error `2022-05-14T10:02:47Z: Build 'azure-arm.ubuntu' errored after 740 milliseconds 818 microseconds: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group staging-packer-images
`

**Comment by dduportal** [comment]
Ref. https://infra.ci.jenkins.io/blue/organizations/jenkins/infra-tools%2Fpacker-images/detail/main/78/pipeline/244

**Comment by dduportal** [comment]
Root cause: https://github.com/jenkins-infra/packer-images/pull/221/files#diff-a801a318a6ef10e1f344c450dfc3288fe6abfe3092af6ad74093fc6202571a56R89

=> changed the image naming from `ubuntu-20` to `ubuntu-20.04`.

Todo list for fixing:
- [ ] Create the new `ubuntu-20.04` image in the `staging` Azure image library (should fix the main build)
- [ ] Create the new `ubuntu-20.04` image in the `prod` Azure image library (To avoid failing the next release build)
- [ ] Update the updatecli and Azure VM Jenkins configs in jenkins-infra/jenkins-infra + jenkins-infra/kubernetes-management to use the new name

**Comment by lemeurherve** [comment]
prod image manually created, see https://github.com/jenkins-infra/packer-images/pull/231#issuecomment-1126691809

**Comment by dduportal** [comment]
Rest of images should be created and tracked in Terraform with https://github.com/jenkins-infra/azure/pull/189

**Comment by dduportal** [comment]
Damn, it fails with the error

```
│ Error: creating/updating Shared Image: (Image Name "jenkins-agent-ubuntu-20" / Gallery Name "dev_packer_images" / Resource Group "dev-packer-images"): compute.GalleryImagesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'galleryImage.properties.eula' is not allowed." Target="galleryImage.properties.eula"
```

**Comment by dduportal** [comment]
OK fixed, gallery created and the principal branch build for packer works !
