### ISSUE TITLE
bug(Windows 2019): Unable to install system's OpenSSH on AWS AMIs

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/packer-images#253]
Build on main branch are failing since a few days with the following error:

```console
==> amazon-ebs.windows: Provisioning with powershell script: ./provisioning/windows-provision.ps1
    amazon-ebs.windows: = Setting up OpenSSH Server
    amazon-ebs.windows: Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
    amazon-ebs.windows: At C:\Windows\Temp\script-62a1ba9d-107e-c1ff-1190-b7e16605f4f2.ps1:71 char:1
    amazon-ebs.windows: + Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
    amazon-ebs.windows: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    amazon-ebs.windows:     + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    amazon-ebs.windows:     + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
    amazon-ebs.windows:
==> amazon-ebs.windows: Provisioning step had errors: Running the cleanup provisioner, if present...
```

but only for AWS AMI.

We have to unblock this to be able to deliver changes.

**Comment by lemeurherve** [comment]
We can try this: https://stackoverflow.com/questions/53917787/error-with-windows-10-powershell-get-windowscapability-and-add-windowscapability

**Comment by dduportal** [comment]
Tried different images on AWS and some conclusions to draw:

- This only only affect the 2022-05-25 builds of Windows Server 2019 AWS (all kinds: Base, Base Full with UI, Core, Core Full, Base Containers, Core Containers, and also their counterparts EC2LaunchConfig Base/Core etc.).
- Windows Server 2022 does not have the issue, neither Azure's Server 2019
- It works if we pin to the 2022-05-11: just a bit longer since all the windows updates have to be applied first

**Comment by dduportal** [comment]
- Tried the method described in @lemeurherve 's comment earlier: it does not work alas
- Tried all the methods described in https://github.com/MicrosoftDocs/windowsserverdocs/issues/2074 : none is working

**Comment by dduportal** [comment]
Hotfix PR on https://github.com/jenkins-infra/packer-images/pull/254 to unblock (short term). 
Keeping the issue here open until either we introduce an updatecli system, or an alert to check the next AWS version.
