### ISSUE TITLE
Install choco on its own first, then all following tools with a specific choco data structure

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/packer-images#270]
> As chocolatey is needed, we have to ensure the correct order. Adding an element after the block l243 would be fragile: anyone reordering or renaming this code would make this fail.

> The struct l243 is built to "download -> (eventually) unarchive -> install -> (eventually) run post commands -> (eventually) add to path. I felt like it was not fit to run a chocolatey (or set of) chocolatey commands only.

WDYT of installing choco on its own first, then all these tools with a specific choco data structure?

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/packer-images/pull/269#discussion_r914553300_

**Comment by dduportal** [comment]
Great idea: installing choco as a first step would help a lot.

(Side note: on the Linux case, ASDF is used, but I managed to make it idempotent: each "install_XXX" function that requires asdf should call the instruction `install_asdf`)

**Comment by dduportal** [comment]
Closed by #225
