### ISSUE TITLE
Do not use Windows Git 2.37.2

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/packer-images#316]
### Service(s)

ci.jenkins.io

### Summary

Based on the comments in [git for Windows issue 3981](https://github.com/git-for-windows/git/pull/3981), we should not install git for Windows 2.37.2.  It says:

> The last rebase somehow managed to remove half (well, probably more than half) of Git for Windows' history. After noticing it while running the microsoft/git rebase, I downgraded v2.37.2.windows.1 back to pre-release, and manually tweaked the rebase script to avoid the problem areas

Git for windows 2.37.1 is working well on ci.jenkins.io.  No rush to upgrade to git for Windows 2.37.2.

The MinGit for Windows 2.37.2 version that I've been running on five of my Windows 10 computers has not shown any issues, but it also has not been through any specific or detailed testing in search of issues.

### Reproduction steps

1. Do not install git for Windows 2.37.2 so that we avoid issues

**Comment by dduportal** [comment]
> MinGit 2.37.2.2 is available to replace MinGit 2.37.2

Sounds like there is an issue in the regexp that we use for the automatic "updatecli" process:

https://github.com/jenkins-infra/packer-images/blob/main/updatecli/updatecli.d/git-windows.yml#L28

Only matches the tag [`v2.37.1.windows.1`](https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1) but not the tag [`v2.37.2.windows.2`](https://github.com/git-for-windows/git/releases/tag/v2.37.2.windows.2)

**Comment by dduportal** [comment]
Closing as 2.37.3+ was applied (#327 / #328 )
