### ISSUE TITLE
set locale from packer

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/packer-images#343]
As per https://github.com/jenkins-infra/packer-images/pull/341

Improvement proposal for a subsequent PR that would centralize the locale selection: 

- Set the locale value (`en_US.UTF-8`) as a packer variable in here: https://github.com/jenkins-infra/packer-images/blob/main/variables.pkr.hcl
- Update https://github.com/jenkins-infra/packer-images/blob/main/sources.pkr.hcl#L84-L86  to use this variable when setting up the container default metadatas from this new variables
- Pass the packer variable to a shell environment variable by adding an entry here: https://github.com/jenkins-infra/packer-images/blob/main/locals.pkr.hcl#L23-L31
-  Update the script here to:
  - Move the "locale generation" from docker-only to ubuntu provisioning (only the locale package install is docker only) and set it up to use the variable
  - Check for Windows

_Originally posted by @dduportal in https://github.com/jenkins-infra/packer-images/pull/341#pullrequestreview-1110274614_

**Comment by smerle33** [comment]
> * Check for Windows

check in place here : https://github.com/jenkins-infra/acceptance-tests/pull/33
need to discuss what locale we plan to use under windows ... for now : 
`Default locale: en_US, platform encoding: Cp1252`

**Comment by dduportal** [comment]
UTF-8 all the way \o/
