### ISSUE TITLE
bug: playwright dependencies installation (or tests) leaves a set of unwanted files in the `jenkins` user home directory

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/packer-images#584]
While working on https://github.com/jenkins-infra/jenkins-infra/pull/2744, @lemeurherve caught that there was unexpected elements in the `/home/jenkins` user home directory, related to the `playwright` installation (or testing) process:

```
+ ls -la /home/jenkins
# ...
 drwxrwxr-x 195 jenkins jenkins  4096 Apr  3 13:20 node_modules
 drwxrwxr-x   4 jenkins jenkins  4096 Apr  3 13:19 .npm
 -rw-rw-r--   1 jenkins jenkins    60 Apr  3 13:20 package.json
 -rw-rw-r--   1 jenkins jenkins 97457 Apr  3 13:20 package-lock.json
# ...
```

Particularly:

```
+ cat /home/jenkins/package.json
 {
   "dependencies": {
     "playwright-test": "^8.2.0"
   }
 }
```

We should have these elements removed

**Comment by hainenber** [comment]
hi @dduportal, I'd like to volunteer working on this. Can it be assigned to me? Thanks!

**Comment by dduportal** [comment]
> hi @dduportal, I'd like to volunteer working on this. Can it be assigned to me? Thanks!

Yes with pleasure, please proceed :)

**Comment by hainenber** [comment]
From my investigation, `playwright` is installed during this [sanity check](https://github.com/jenkins-infra/packer-images/blob/main/provisioning/ubuntu-provision.sh#L674). I wonder if it makes sense. 

If there are downstream parts where `playwright` is indeed installed, we can lift off the version checking of `playwright` in other means than installing another dependency for it, IMO.

@smerle33 sorry for pinging but it'd be great if you can provide the context for it. Thanks!

**Comment by hainenber** [comment]
I've tested locally and found out installation of sole `playwright-test` would not provision `playwright` right off the bat so there must be downstream parts that install it. It's possible to say that we can [remove installing of `playwrigh-test` just for vesion-checking `playwright`](https://github.com/jenkins-infra/packer-images/pull/801/files#diff-485e38775f798b1a8181ceada9148f140b6487f8bcadc39867338df791d06ca6L673-L674)

Please have a look and let me know any of your concerns. Thanks!

**Comment by dduportal** [comment]
A bit of context here (that could help): https://github.com/jenkins-infra/helpdesk/issues/3345.

> I've tested locally and found out installation of sole playwright-test would not provision playwright right off the bat so there must be downstream parts that install it. It's possible to say that we can [remove installing of playwrigh-test just for vesion-checking playwright](https://github.com/jenkins-infra/packer-images/pull/801/files#diff-485e38775f798b1a8181ceada9148f140b6487f8bcadc39867338df791d06ca6L673-L674)

You have understood the idea: we want to install the dependencies (mainly apt packages) needed by `playwright` but not playwright itself.
The challenge was to know the exact list of apt packages  to retrieve (which changes over time of course).
=> Hence the reason of having the `playwright-test` during the sanity checks to "simulate" what a downstream user would do.

From there we have to possible roads:

- Install playwright itself, which require installing it with a pinned version
  - Pro: Less tooling problem like here
  - Con: we'll have to keep it up to date, and follow downstream users requirements

- Keep the current provisioning and accept that the sanity check is what we expect
  - Pro: we keep the initial design with freedom for downstream users
  - Con: we have to add the "cleanup" as part of the sanity check

Note: we started some work a while ago to move the sanity tests outside of the provisioning script, using `goss`. See the initial implementation here. Maybe that would be interesting to move the playwright-test sanity "install + check + cleanup" out of the provisioning script and into the goss test harness.

WDYT?
