### ISSUE TITLE
JDK 8u292 can break plugin tests that use the Java Keystore

### ISSUE THREAD

**Issue by chriskilding** [jenkins-infra/packer-images#77]
JDK 8u292 inadvertently removed the PBEWithSHA1AndDESede Keystore algorithm. This can break plugin tests that use the Java Keystore.

When those tests run with the Jenkins JDK8 configuration on on ci.jenkins.io, errors will be seen like:

    java.security.KeyStoreException: Key protection  algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede

So we need to either upgrade or downgrade the JDK8 version on ci.jenkins.io to address this.

**Comment by chriskilding** [comment]
JDK 8u302 is intended to fix this problem. The upstream OpenJDK version of 8u302 was released on 20 July, and the various JDK distributions should bring it in soon. That would be the upgrade option.

**Comment by chriskilding** [comment]
OpenJDK bug report: https://bugs.openjdk.java.net/browse/JDK-8266261

**Comment by timja** [comment]
You able to send a PR?

**Comment by chriskilding** [comment]
If this is the right place to apply it then yep

**Comment by chriskilding** [comment]
Which JDK distro do we use?

**Comment by dduportal** [comment]
Hello @chriskilding thanks for reporting!

- For Linux (Ubuntu 20.04), we use the distribution's package: https://github.com/jenkins-infra/packer-images/blob/main/scripts/ubuntu-20-provision.sh#L97
- For Windows, we use AdoptOpenJDK: https://github.com/jenkins-infra/packer-images/blob/main/scripts/windows-2019-provision.ps1#L86
- The version is commonly defined in this file: https://github.com/jenkins-infra/packer-images/blob/main/.auto.pkrvars.hcl#L4 

I realize that we might want to switch the Ubuntu template to use AdoptOpenJDK so the updates and behaviour would be common between the 2 operating systems.

@chriskilding are you ok to open a PR? If you are not sure we can help or even pair with you on this topic.
